### ISSUE TITLE
Feature request: Add `sftp open` command

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis-cli#108]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Add `trellis sftp open <env> <site>` which opens sftp gui clients.

Cyberduck example: 
```
$ trellis sftp open production example.com --app=cyberduck
# Invoke `open sftp://web@111.222.333.444:22/srv/www/example.com/`
```

## Additional context

Similar to:
- https://github.com/roots/trellis-cli/pull/100
- https://github.com/roots/trellis-cli/blob/5c59781174591cea217c849da0995c66479d747c/cmd/alias.go#L48-L49

**Comment by swalkinshaw** [comment]
This seems like a pretty niche command to me. Would be a perfect fit for a plugin if we want to revisit that.

**Comment by TangRufus** [comment]
Done in https://github.com/ItinerisLtd/trellis-cyberduck
