### ISSUE TITLE
Feature request: add `clear cache` command to clear blade cache

### ISSUE THREAD

**Issue by code23-barna** [roots/trellis-cli#111]
Clearing the blade cache from `site/web/app/uploads/cache` is a recurring job I do manually. Is there a chance to extend the CLI to handle that?

* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Feature request: to add clear blade cache command.

## Motivation

Clearing the blade cache from `site/web/app/uploads/cache` is a recurring job I do manually. Is there a chance to extend the CLI to handle that?

**Comment by swalkinshaw** [comment]
If it's recurring can you set a cron job to run it periodically? 

This is a very Blade/Sage specific command and trellis-cli (and Trellis itself) do not assume Sage so we wouldn't add this specific of a feature.
