### ISSUE TITLE
No usable default provider could be found for your system.

### ISSUE THREAD

**Issue by chrish-d** [roots/trellis-cli#121]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

After following the steps to install on the Github README, I get the following error when running `trellis up`

> No usable default provider could be found for your system.

## Steps to reproduce

1. Install latest version of Vagrant and Virtualbox
1. Run `trellis new example.test`
2. `cd` into the example.test directory
3. Run `trellis up`

**Comment by robrecord** [comment]
Confirmed this fixed this issue. Thanks @swalkinshaw !
