### ISSUE TITLE
Error on `trellis new`: virtualenv & ansible galaxy "no such file"

### ISSUE THREAD

**Issue by robrecord** [roots/trellis-cli#124]
* [*] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [*] This request isn't a duplicate of an existing issue
* [*] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [*] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When I create a new site using trellis, I get two errors:
```
Error creating virtualenv: fork/exec /usr/local/bin/virtualenv: no such file or directory
Error running ansible-galaxy: fork/exec /usr/local/bin/ansible-galaxy: no such file or directory
```

## Steps to reproduce

1. `trellis new` with or without parameters
2. Give installer any information required

**Expected behavior:** [What you expect to happen]

Site created with no errors

**Actual behavior:**

Example command:

```bash
trellis new ~/testtest.ccom
```
Output:
```
Creating new Trellis project in /Users/robrecord/testtest.ccom

Site domain [testtest.ccom]: 

✔ www.testtest.ccom

Fetching latest versions of Trellis and Bedrock...
Creating virtualenv in /Users/robrecord/testtest.ccom/trellis/.trellis/virtualenv
Error creating virtualenv: fork/exec /usr/local/bin/virtualenv: no such file or directory

Error running ansible-galaxy: fork/exec /usr/local/bin/ansible-galaxy: no such file or directory

testtest.ccom project created with versions:
  Trellis v1.4.0
  Bedrock v1.13.5
```

**Reproduces how often:** 100% since today.

## Versions

- trellis-cli v0.9.0 and HEAD-56abf23
- Trellis v1.4.0
- Bedrock v1.13.5
- go1.14.4 darwin/amd64
- MacOS Catalina 10.15.5 (19F101)

## Additional information

If you could tell me how to isolate this so that I can prove whether it's my setup or trellis code, that would help me.

**Comment by swalkinshaw** [comment]
Thanks for the detailed issue @robrecord 

```plain
Creating virtualenv in /Users/robrecord/testtest.ccom/trellis/.trellis/virtualenv
Error creating virtualenv: fork/exec /usr/local/bin/virtualenv: no such file or directory
```

Judging by this output, trellis-cli detected that `virtualenv` exists (and at `/usr/local/bin/virtualenv`) but then fails to find it 🤔 

Could you please run `which virtualenv` in your shell and show what it returns? Also you could try running whatever path it returns (assuming it does).

**Comment by robrecord** [comment]
Thank you. This game me what I needed to solve the issue.

```
$ which virtualenv

/usr/local/bin/virtualenv
```
```
$ /usr/local/bin/virtualenv
zsh: /usr/local/bin/virtualenv: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
```

Python 3.7... interesting. My version is 3.8.

I looked this up and found this answer: https://superuser.com/a/1380419/48308

The solution was to remove virtualenv and reinstall it using pip3.

```
$ pip install virtualenv
$ pip uninstall virtualenv
$ pip3 install virtualenv
```

Then running `virtualenv` directly worked correctly and so did `trellis new`!

Looks like my virtualenv was still trying to use python 3.7 after (I assume) homebrew upgraded it to 3.8. Apparently this is normal, according to the internet; I will bear in mind for next time this troubleshooting step to update the interpreter.

Thanks for your assistance again, @swalkinshaw.

**Comment by MikeiLL** [comment]
For me what solved the problem was deleting the `trellis/.trellis` directory. Problem occurred after moving the location of the trellis (and site) directory (after having run `vagrant destroy`). Seemed simpler to destroy and rebuild than tracking down the paths where the VM gets defined.
