### ISSUE TITLE
Feature request: Add `branch` option to deploy command

### ISSUE THREAD

**Issue by mike-sheppard** [roots/trellis-cli#125]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Add a branch option to the `trellis deploy` command to override the deployed branch

Example:
```bash
trellis deloy staging example.com --branch=feature/branch-name
```

## Motivation

Simplify the deployment of custom branches. As a team we'll deploy our individual feature branches on staging before merging as part of our code review / QA process, it'd be great if we could simplify it with the `trellis-cli`.

## Additional context

Currently we achieve this by passing it through`-e EXTRA_VARS, --extra-vars` as discussed [in the discourse](https://discourse.roots.io/t/any-way-to-specify-branch-as-command-line-deploy-argument-to-override-default-branch-setting-in-wordpress-sites-yml/11937/2)

```diff
# group_vars/staging/wordpress_sites.yml
- branch: staging
+ branch: "{{ branch | default('staging') }}"
```

```bash
$ ansible-playbook deploy.yml -e "site=example.com env=staging branch=feature/new-stuff"
```

Thanks + this tool is v. much appreciated! :)

**Comment by swalkinshaw** [comment]
I've opened a PR on Trellis as the first part of this: https://github.com/roots/trellis/pull/1204
