### ISSUE TITLE
-bash: PROMPT_COMMAND: line 3: syntax error near unexpected token `;'

### ISSUE THREAD

**Issue by MikeiLL** [roots/trellis-cli#128]
My use of trellis-cli has been limited. It's wonderful.

Trying to get auto-completion working in bash with following error:

```
-bash: PROMPT_COMMAND: line 3: syntax error near unexpected token `;'
-bash: PROMPT_COMMAND: line 3: `setLastCommandState;{;        [[ $- =~ x ]] && {;          \set +x; __trellis_cli_hook precmd 2>&3; \set -x;;        } || {;          __trellis_cli_hook precmd 2>&3;;        };      } 4>&2 2>/dev/null 3>&4;;      shell_session_history_check; update_terminal_cwd;setGitPrompt'
```

This occurs after I have added `eval "$(trellis shell-init bash)"` to `~/.bashrc`.

None of the above code seems to exist in the trellis-cli codebase, and I'm confused as to what's going on.

I think I have solved the issue already, the problem was that the `eval` line was in the bash config script _before_ the scripting to enable brew line completion. 

Would it make sense to specify, in the Docs, that the `eval` line needs to _follow_ the `if type brew &>/dev/null; then` block?

**Comment by swalkinshaw** [comment]
You said this was for "auto=completion":
> Trying to get auto-completion working in bash with following error:

But the command was for the virtualenv shell integration feature? `eval "$(trellis shell-init bash)"`

Just want to make sure which feature caused this error. I'm assuming it's `shell-init` and not autocomplete?

> Would it make sense to specify, in the Docs, that the eval line needs to follow the if type brew &>/dev/null; then block?

Sorry, can you explain this more?

**Comment by MikeiLL** [comment]
> You said this was for "auto=completion":
> 
> > Trying to get auto-completion working in bash with following error:
> 
> But the command was for the virtualenv shell integration feature? `eval "$(trellis shell-init bash)"`
> 
> Just want to make sure which feature caused this error. I'm assuming it's `shell-init` and not autocomplete?

Correct. I had misunderstood.
When I added `eval "$(trellis shell-init bash)"` to the `~/.bashrc` file and sourced it, the error was displayed in the terminal. It would be displayed again when I ran `trellis`. 
> 
> > Would it make sense to specify, in the Docs, that the eval line needs to follow the if type brew &>/dev/null; then block?
> 
> Sorry, can you explain this more?

When I moved `eval "$(trellis shell-init bash)"` to _below_ the lines for enabling command-line completion in the `~/.bashrc` file, all behaves as expected.

Perhaps the docs should specify that `eval "$(trellis shell-init bash)"` needs to follow the aforementioned lines (if that is indeed the case).

**Comment by swalkinshaw** [comment]
Interesting 🤔 I wouldn't think the order should matter but apparently it does. Can you paste the entire relevant section of your bash config here so it's obvious? I can update the README too

I'm glad it works after that though.

**Comment by MikeiLL** [comment]
Just noticed this line in the `bashrc` file: `complete -C /usr/local/bin/trellis trellis, apparently from a previous install.

I will check and see if that is what was causing the issue...

**Comment by MikeiLL** [comment]
Pretty sure that I can confirm that for me, when the `eval` line is above the `if (type brew` block, the error message is displayed.

Not only does it display, but it persists in the same terminal session, even after having moved the `eval` line below the `brew` block. Strange.

What works for me is:

```
# For Homebrew Line Completion
# source: https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi

# Trellis CLI Auto Complete
eval "$(trellis shell-init bash)"
```

Sourced in a fresh (untainted) terminal session.

In case it offers any insight, here's the rest of my `~/.bashrc` file:

```
# use Node's blc to check broken links
# see: https://github.com/stevenvachon/broken-link-checker

# In case there's anything in there we need:
source ~/.profile

# this might make gettext available in env
PATH=$PATH:/Applications/Poedit.app/Contents/MacOS

PATH=/usr/local/lib:/usr/local/bin:/usr/local/sbin:~/bin
PATH=$PATH:/Library/Python/2.7/site-packages/

PATH="$HOME/.npm-packages/bin:$PATH"
PATH="$HOME/.npm/bin:$PATH"

# for Rosuav's shed
PATH=$PATH:~/shed
PATH=$PATH:/Library/TeX/texbin/

PATH="$PATH:$HOME/.composer/vendor/bin"

# For Homebrew
PATH="/usr/local/opt/python/libexec/bin:$PATH"

# for lilypond
PATH=$PATH:~/bin:/usr/texbin
PATH=/usr/local/texlive/2016/bin/x86_64-darwin:$PATH

PATH="/usr/local/opt/valet-php@7.2/bin:$PATH"
PATH="/usr/local/opt/valet-php@7.2/sbin:$PATH"
PATH="/usr/local/opt/php@7.2/bin:$PATH"

PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Keybase.app/Contents/SharedSupport/bin:/usr/local/MacGPG2/bin:
PATH="/usr/local/bin:/usr/local/sbin:~/bin:/usr/bin:$PATH"

export PATH

# Other Environment Variables

export LDFLAGS="-L/usr/local/opt/valet-php@7.2/lib"
export CPPFLAGS="-I/usr/local/opt/valet-php@7.2/include"

# I think this is for VIM Colors
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

export SVN_EDITOR=vim

export VAGRANT_HOME=/Volumes/Oggun/vagrant_home

export NVM_DIR="/Users/mikekilmer/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
export NODE_PATH=/usr/local/bin/node:/Users/mikekilmer/.nvm/versions/node/v6.9.4/lib/node_modules

export COMPOSER_DISABLE_XDEBUG_WARN=1

# For VirtualEnvWrapper
export WORKON_HOME=$HOME/Envs
export PROJECT_HOME=$HOME/Devel
export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
source /usr/local/bin/virtualenvwrapper.sh

# added by travis gem
[ -f /Users/mikekilmer/.travis/travis.sh ] && source /Users/mikekilmer/.travis/travis.sh

# Aliases here
# COMMANDS
alias random='openssl rand -base64 32 | pbcopy'
# removed for brevity


# from Rosuav (thought this might be a conflict, but doesn't seem to be... not currently using it.)
checkdir() {
   [ -n "$VIRTUAL_ENV" ] && ! [[ `pwd` =~ `dirname $VIRTUAL_ENV`* ]] && echo Deactivating venv $VIRTUAL_ENV... && deactivate
   [ -z "$VIRTUAL_ENV" -a -d env ] && echo Activating venv `pwd`/env... && source env/bin/activate
}
# this is preventing new tab from opening in same directory.
# PROMPT_COMMAND=checkdir

# as per http://hackercodex.com/guide/python-development-environment-on-mac-osx/
# pip should only run if there is a virtualenv currently activated
gpip(){
   PIP_REQUIRE_VIRTUALENV="0" pip3 "$@"
}


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mikekilmer/google-cloud-sdk/path.bash.inc' ]; then . '/Users/mikekilmer/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mikekilmer/google-cloud-sdk/completion.bash.inc' ]; then . '/Users/mikekilmer/google-cloud-sdk/completion.bash.inc'; fi

# For informative git prompt from https://github.com/magicmonty/bash-git-prompt
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  GIT_PROMPT_ONLY_IN_REPO=1
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi
GIT_PS1_DESCRIBE_STYLE=branch

# For Homebrew Line Completion
# source: https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi

# Trellis CLI Auto Complete
eval "$(trellis shell-init bash)"
```

**Comment by swalkinshaw** [comment]
Weird! Oddly enough I have *never* added that Homebrew shell completion code and all my completions work (as far as I know) 🤔 

To summarize, the solution for you is to ensure that `eval "$(trellis shell-init bash)"` is after the Homebrew completion code? Nothing else right?

**Comment by MikeiLL** [comment]
> To summarize, the solution for you is to ensure that `eval "$(trellis shell-init bash)"` is after the Homebrew completion code? Nothing else right?

That _seems_ to be the case. Thanks for always being so attentive, @swalkinshaw

**Comment by swalkinshaw** [comment]
Going to close this for now. If it comes up again I might clarify things in the docs.
