### ISSUE TITLE
cannot pickle '_io.TextIOWrapper' object

### ISSUE THREAD

**Issue by MikeiLL** [roots/trellis-cli#129]
Using a version of Trellis from February 2020.

`python 3.8`
`ansible 2.8.15`

I was getting this error running in my native environment: 

`crypt.crypt not supported on Mac OS X/Darwin, install passlib python module`

So setup the venv with `trellis init` (so dope!).

Now getting following error on `users` task:

```
TASK [connection : Require manual definition of remote-user] **************************************************************************************************
task path: /Path/To/example.com/trellis/roles/connection/tasks/main.yml:2
ERROR! Unexpected Exception, this is probably a bug: cannot pickle '_io.TextIOWrapper' object
the full traceback was:

Traceback (most recent call last):
  File "/Path/To/example.com/trellis/.trellis/virtualenv/bin/ansible-playbook", line 110, in <module>
    exit_code = cli.run()
  File "/Path/To/example.com/trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible/cli/playbook.py", line 123, in run
    results = pbex.run()
  File "/Path/To/example.com/trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible/executor/playbook_executor.py", line 169, in run
    result = self._tqm.run(play=play)
  File "/Path/To/example.com/trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible/executor/task_queue_manager.py", line 249, in run
    play_return = strategy.run(iterator, play_context)
  File "/Path/To/example.com/trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible/plugins/strategy/linear.py", line 306, in run
    self._queue_task(host, task, task_vars, play_context)
  File "/Path/To/example.com/trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible/plugins/strategy/__init__.py", line 323, in _queue_task
    worker_prc.start()
  File "/Path/To/example.com/trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible/executor/process/worker.py", line 100, in start
    return super(WorkerProcess, self).start()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_io.TextIOWrapper' object
```

**Comment by swalkinshaw** [comment]
Did you ever solve this?

**Comment by MikeiLL** [comment]
> Did you ever solve this?

I didn't. Sorry. Also the project was taking over by someone else (for the time being, any way.) I suggest we close unless it comes up again.

**Comment by swalkinshaw** [comment]
no problem, I never replied because it was a weird one 🙈

**Comment by TangRufus** [comment]
> cannot pickle '_io.TextIOWrapper' object

I resolved it by:
- merging roots/trellis#master into my Trellis repo, and
- update Ansible

Real culprit is unknown.

**Comment by MikeiLL** [comment]
Thanks.

> > cannot pickle '_io.TextIOWrapper' object
> 
> I resolved it by:
> 
> * merging roots/trellis#master into my Trellis repo, and
> * update Ansible
> 
> Real culprit is unknown.

    1. within `trellis` directory, run `git init` (as main `.git` home is in the dir above that)
    2. `git init && git add -A && git commit`
    3. `git add remote upstream git@github.com:roots/trellis.git`
    4. `git fetch upstream master`
    5. `git merge upstream master`
    6. Git will report many conflicts
    7. `git mergetool` I am using [kdiff](https://www.mzoo.org/git-mergetool/)
    8. I kept my local files for php 7.3, mariadb, etc

Always insightful for me to look at the changes that have been made and get more familiar with Trellis under the hood.

The changes that seem most likely to have been relevant to this error are:

    lib/trellis/plugins/callback/output.py (Remote)

Was
    except ImportError:
        ansible_path = os.getenv('ANSIBLE_CONFIG', os.getcwd())
Now
    except ImportError:
        ansible_config_path = os.getenv('ANSIBLE_CONFIG')
        ansible_path = os.path.dirname(ansible_config_path) if ansible_config_path else os.getcwd()

Also added
```
DOCUMENTATION = '''
    callback: output
    type: stdout
    short_description: Custom output for Trellis
    extends_documentation_fragment:
      - default_callback
'''
```

    lib/trellis/plugins/callback/vars.py (Remote)
Add
    from ansible import context
Replace
        # handle Ansible 2.7 and 2.8 cases by normalizing each into a dict
        try:
            from ansible import context
            self._options = context.CLIARGS
        except ImportError:
            self._options = vars(cli.options) if cli else {}
With 
	self._options = context.CLIARGS

    lib/trellis/plugins/vars/version.py (Remote)
Update version requirement to 2.8.0
    version_tested_max = '2.9.10'
Plus a spelling correction (you Ansible version)

    lib/trellis/utils/output.py (Remote)
From
    ansible_path = os.getenv('ANSIBLE_CONFIG', os.getcwd())
To
    ansible_config_path = os.getenv('ANSIBLE_CONFIG')
    ansible_path = os.path.dirname(ansible_config_path) if ansible_config_path else os.getcwd()

    lib/trellis/vagrant.rb (Remote)
From
	ENV['ANSIBLE_CONFIG'] = ANSIBLE_PATH
To
	ENV['ANSIBLE_CONFIG'] = File.join(ANSIBLE_PATH, 'ansible.cfg')

    requirements.txt (Remote)
From
    ansible>=2.7.2,<2.9
To
    ansible>=2.8.0,<3.0 

    9. Remove `trellis/.git` directory
    10. `git status`

There are a few new files, in my case:

	.ansible-lint
	.circleci/
	.gitattributes
	deploy-hooks/build-before.yml
	group_vars/development/security.yml
	roles/wordpress-install/tasks/dotenv.yml

I had made some notes about items from `main.yml` being moved to security. Also noticed some references to `dotenv` which I think I kept.

So added the first three files to `trellis/.gitignore` and the others to my repository.

**Comment by swalkinshaw** [comment]
Interesting, okay so it's usually some sort of mismatch between Ansible related code in Trellis and the Ansible version (and maybe Python). Basically... it's complicated and hard to know exactly 😞

**Comment by codepuncher** [comment]
I know this issue is closed, but (for me at least), it's still an issue and hopefully, I can (somehow) help with resolving this in some way.

I've recently moved to MacOS (first timer) from Linux so I wonder if there's some sort of system configuration related issue that I've created.

Out of `virtualenv` / Trellis directory
```
➜ python --version
Python 2.7.16
```

Inside of `virtualenv` / Trellis directory
```
➜ python --version
Python 3.9.2
```

The command that I am running is `trellis dotenv` (after having already run `trellis init` without issue).

I did previously use `pyenv` a week or so ago for my initial macOS setup but I have since removed it (it was causing me issues with `trellis-cli`) and I'm just relying on the pre-shipped Python 2 and `python@3.9` from Homebrew as it's a dependency for some packages.
I have also tried changing the Ansible version in `requirements.txt` to bump down a few versions, `rm -rf .trellis/virtualenv && cd .. && cd trellis && trellis init && trellis dotenv` but it made no difference.

Aside from [these](https://github.com/roots/trellis/commit/654518c94e3f33bd9cd587ff0317cbb71d2112b6) [commits](https://github.com/roots/trellis/pull/1280/files), I am up-to-date with `master`.

Is there any information or things I can provide to help with this? Another colleague has the same issue. Another colleague doesn't, but he never runs `trellis init` and relies on his system packages instead.

**Comment by MikeiLL** [comment]
If it helps, this is my ansible version:

```
ansible --version
ansible 2.10.6
  config file = None
  configured module search path = ['/Users/mikekilmer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = trellis/.trellis/virtualenv/lib/python3.8/site-packages/ansible
  executable location = trellis/.trellis/virtualenv/bin/ansible
  python version = 3.8.5 (default, Feb 23 2021, 16:54:24) [Clang 10.0.1 (clang-1001.0.46.4)]
```

I actually am using pyenv as of a couple of weeks ago because of a conflict with a python project.

```
$which python
/Users/mikekilmer/.pyenv/shims/python
$which python2
/Users/mikekilmer/.pyenv/shims/python2
```
I'm using
```
➜ python --version
Python 3.8.5
```

**Comment by codepuncher** [comment]
I was just going through my project with the issue to share my ansible version(s) and I have discovered that `pyenv` has been unknowingly installed by Homebrew (which I installed a week or so ago).

```zsh
trellis on  master via .trellis
➜ trellis exec ansible --version                                                                                                                                                                         17:13:17
ansible 2.8.19
  config file = /Users/my-user/Code/wordpress/my-project/trellis/ansible.cfg
  configured module search path = ['/Users/my-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/my-user/Code/wordpress/my-project/trellis/.trellis/virtualenv/lib/python3.9/site-packages/ansible
  executable location = /Users/my-user/Code/wordpress/my-project/trellis/.trellis/virtualenv/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:26:09) [Clang 12.0.0 (clang-1200.0.32.29)]

trellis on  master via .trellis took 5s
➜ ansible --version                                                                                                                                                                                17:13:27
ansible 2.8.19
  config file = /Users/my-user/Code/wordpress/my-project/trellis/ansible.cfg
  configured module search path = ['/Users/my-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/my-user/Code/wordpress/my-project/trellis/.trellis/virtualenv/lib/python3.9/site-packages/ansible
  executable location = /Users/my-user/Code/wordpress/my-project/trellis/.trellis/virtualenv/bin/ansible
  python version = 3.9.2 (default, Feb 24 2021, 13:26:09) [Clang 12.0.0 (clang-1200.0.32.29)]

trellis on  master via .trellis
➜ cd ..                                                                                                                                                                                            17:13:31
[trellis] deactivated env

Code/wordpress/my-project
➜ ansible --version                                                                                                                                                                                17:13:34
zsh: /Users/my-user/.local/bin/ansible: bad interpreter: /Users/my-user/.pyenv/versions/3.8.7/bin/python3.8: no such file or directory

Code/wordpress/my-project
➜ brew list
...
pyenv
...

Code/wordpress/my-project took 11s
➜ brew info pyenv                                                                                                                                                                                  17:14:07
pyenv: stable 1.2.24 (bottled), HEAD
Python version management
https://github.com/pyenv/pyenv
/usr/local/Cellar/pyenv/1.2.23 (738 files, 2.6MB) *
  Poured from bottle on 2021-03-13 at 23:52:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pyenv.rb
License: MIT
==> Dependencies
Required: autoconf ✔, openssl@1.1 ✔, pkg-config ✔, readline ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 133,910 (30 days), 327,824 (90 days), 959,417 (365 days)
install-on-request: 130,652 (30 days), 319,646 (90 days), 925,334 (365 days)
build-error: 0 (30 days)
```

I'll try removing `pyenv` soon and see how that goes.
