### ISSUE TITLE
The roles/nginx/defaults/main.yml file seemed to be outdated

### ISSUE THREAD

**Issue by MikeiLL** [roots/trellis-cli#131]
I ran `trellis init` on Sept 9th.

Provisioning a DO Ubuntu20 droplet. Incorporated some of the updates outlined in [#1180](https://github.com/roots/trellis/issues/1180).

`nginx : Add Nginx PPA` task was failing. Source was set to:

```
nginx_ppa: "ppa:nginx/mainline"
```

When I updated to what I think is a more up-to-date content for that file:

```
---
nginx_keyserver: "https://nginx.org/keys/nginx_signing.key"
nginx_keyserver_id: "ABF5BD827BD9BF62"
nginx_ppa: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
nginx_package: nginx
nginx_conf: nginx.conf.j2
nginx_path: /etc/nginx
nginx_worker_connections: 8000
nginx_logs_root: /var/log/nginx
nginx_user: www-data www-data
nginx_fastcgi_buffers: 8 8k
nginx_fastcgi_buffer_size: 8k
nginx_fastcgi_read_timeout: 120s

# Fastcgi cache params
nginx_cache_path: /var/cache/nginx
nginx_cache_key_storage_size: 10m
nginx_cache_size: 250m
nginx_cache_inactive: 1h
```

The task succeeds.

**Comment by swalkinshaw** [comment]
Closing since this is a Trellis issue (right?) and you commented at https://github.com/roots/trellis/issues/1180#issuecomment-690598170

**Comment by MikeiLL** [comment]
> Closing since this is a Trellis issue (right?) and you commented at [roots/trellis#1180 (comment)](https://github.com/roots/trellis/issues/1180#issuecomment-690598170)

It's fine to close it. I don't know where the codebase is pulled from when running `trellis init`. It seems odd that I would have had a file that doesn't match Trellis master branch, which it looks like `roles/nginx/default/main.yml` didn't on Sept 8th. It looked like that file was changed prior to that date.

**Comment by swalkinshaw** [comment]
Ah, `trellis init` uses the latest *release* of Trellis and not master so that explains it. Ideally in the future we can provide an option to specify a specific version or `master`.

**Comment by MikeiLL** [comment]
> Ah, `trellis init` uses the latest _release_ of Trellis and not master so that explains it. Ideally in the future we can provide an option to specify a specific version or `master`.

Ah. So, if anything, "master" is likely to be ahead of the latest release, correct?

**Comment by swalkinshaw** [comment]
Yep almost always. It defaults to the latest released version because those should be more stable than `master`.
