### ISSUE TITLE
Define Trellis Release

### ISSUE THREAD

**Issue by devotoare** [roots/trellis-cli#138]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Add the ability to define Trellis release, either by tag or by commit.

## Motivation

With the Composer 2 release and subsequent fix in Trellis, that update still hasn't been pushed to a release. Even the official docs use a git clone of master as the official way to get Trellis. Adding a specific version or preference option in the CLI would help `trellis new` be more useful, as right now it's not actually working out of the box.

## Additional context

Not sure if this should be a CLI feature or whether Trellis core just needs to get smaller releases more often.

**Comment by swalkinshaw** [comment]
> Not sure if this should be a CLI feature or whether Trellis core just needs to get smaller releases more often.

Both 😓 

Should definitely have this ability. Maybe it could be solved at the same time as https://github.com/roots/trellis-cli/issues/9
