### ISSUE TITLE
Trellis virtualenv/shell integration breaks with spaces in $PATH

### ISSUE THREAD

**Issue by jeffbyrnes** [roots/trellis-cli#142]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

With a `$PATH` that contains a space, the `virtualenv` integration with `bash` trips on updating `$PATH` correctly:

```
$ eval "$(trellis shell-init bash)"
$ set -xv
$ cd abundanthousingma.org/
cd abundanthousingma.org/
__hookbook_debug_trap "$_"
++ __hookbook_debug_trap -xv
+ cd abundanthousingma.org/
{
        [[ $- =~ x ]] && {
          \set +x; __trellis_cli_hook precmd 2>&3; \set -x;
        } || {
          __trellis_cli_hook precmd 2>&3;
        }
      } 4>&2 2>/dev/null 3>&4;
[trellis] activated env
export VIRTUAL_ENV=/Users/jeffbyrnes/dev/abundanthousingma.org/trellis/.trellis/virtualenv
export PRE_TRELLIS_PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin
-bash: export: `Snitch.app/Contents/Components:/Library/Apple/usr/bin': not a valid identifier
export PATH=/Users/jeffbyrnes/dev/abundanthousingma.org/trellis/.trellis/virtualenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Little Snitch.app/Contents/Components:/Library/Apple/usr/bin
-bash: export: `Snitch.app/Contents/Components:/Library/Apple/usr/bin': not a valid identifier
```

## Steps to reproduce

1. Add a path to `$PATH` that contains a space
2. Enable the Trellis `virtualenv` integration
3. Switch to the project root

**Expected behavior:** The `virtualenv` integration works well.

**Actual behavior:** The integration incorrectly sets `$PATH`

**Reproduces how often:** Always

## Versions

```
$ trellis -v
0.9.1
```

**Comment by jeffbyrnes** [comment]
Looking at the code more closely, seems that it’s a builtin for Go that’s misbehaving:

https://github.com/roots/trellis-cli/blob/f17dd81ec3320559b56bdb98b05f7b7b9f3aff8a/trellis/virtualenv.go#L38-L39

I’ll leave this open for the moment, in case someone else runs across this & is unfamiliar with Go like me.

**Comment by swalkinshaw** [comment]
Thanks for the detailed report.

You're correct that the usage of `os.Setenv` is standard and there's not much we can do there. But I think the problem could actually be here: https://github.com/roots/trellis-cli/blob/c19922c7323fc771ce9da45d18686f22f9b796dc/cmd/venv_hook.go#L24-L26

I'll try out shell escaping these paths before exporting them 🤔

**Comment by swalkinshaw** [comment]
Got a PR up with quoting/escaping the paths https://github.com/roots/trellis-cli/pull/143

I was able to reproduce your issue and this PR seems to fix it.
