### ISSUE TITLE
Discussion: How should we suppport using `trellis-cli` as a library?

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis-cli#149]
#### Problem

As of https://github.com/roots/trellis-cli/commit/5ec0cea57c35b130f76e0ea4976b3acc25703114 `trellis-cli` uses [`mitchellh/cli/ui`](https://github.com/mitchellh/cli/blob/5454ffe87bc5c6d8b6b21c825617755e18a07828/ui.go) everywhere.

Third party developers shouldn't be forced to use `mitchellh/cli`, especially when they are using [`spf13/cobra`](https://github.com/spf13/cobra/) or not intended to print the outputs.

In `itinerisltd/trellis-cyberduck`, I ended up rewriting [`Playbook`](https://github.com/roots/trellis-cli/blob/5ec0cea57c35b130f76e0ea4976b3acc25703114/cmd/playbook.go) and [`AdHocPlaybook`](https://github.com/roots/trellis-cli/blob/5ec0cea57c35b130f76e0ea4976b3acc25703114/cmd/ad_hoc_playbook.go) with [cobra's io writers](https://github.com/ItinerisLtd/trellis-cyberduck/blob/d1bb184abf70e69b55213979a48f525e4edb4d81/lib/io.go#L24-L29). See: https://github.com/ItinerisLtd/trellis-cyberduck/tree/d1bb184abf70e69b55213979a48f525e4edb4d81/lib

#### Discussion

How should we expose/re-structure/refactor `trellis-cli` code, so that developers can use it as a library with minimal dependencies?

**Comment by swalkinshaw** [comment]
> Third party developers shouldn't be forced to use mitchellh/cli

Counter point: why not? Consistency is a big part of a good developer experience, and that becomes way harder if plugins use different CLI libraries.

In my opinion we should just ensure that the trellis-cli package is properly structured to be consumed in plugins so that they don't have to re-invent anything main functionality themselves.
