### ISSUE TITLE
Discussion: Better docker workflow for CI/CD

### ISSUE THREAD

**Issue by TangRufus** [roots/trellis-cli#159]
### Problem

Currently, only @retlehs and I have permissions to push to https://hub.docker.com/r/rootsdev/trellis-cli-dev. Outdated docker images are blocking PRs that use new versions of go or new versions of Trellis, e.g: https://github.com/roots/trellis-cli/pull/157#issuecomment-793384667

### Solution:

Let's discuss. Leave a comment if you have any suggestions.

cc @swalkinshaw

**Comment by swalkinshaw** [comment]
Closing since I've had permission now for a bit. Not sure what else we can do 🤷‍♂️
