### ISSUE TITLE
$ trellis valet link fails

### ISSUE THREAD

**Issue by sangemaru** [roots/trellis-cli#186]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

Trying to run `trellis valet link` on Linux results in the following output error:

```
Running command => valet link --secure mysite                                     
The "--secure" option does not exist.  
link [<name>]
Error running valet link: exit status 1
 ```

## Steps to reproduce

1. [Install Valet - in my case, cpriego/valet-linux]
2. [navigate to a trellis folder]
3. [run `trellis valet link`]

**Expected behavior:** [the Valet alias should link the bedrock folder and configure the .env file]

**Actual behavior:** [trellis-cli passes `--secure` instead of `secure` and fails]

**Reproduces how often:** [100%]

## Versions

You can get this information from referencing `CHANGELOG.md`. Also, please include the OS and what version of the OS you're running.
OS: Ubuntu 20.04
Trellis-cli: 0.9.2

**Comment by TangRufus** [comment]
https://github.com/cpriego/valet-linux doesn't support the `--secure` flag like https://laravel.com/docs/8.x/valet

We should either:
- detect what OS is in use, OR
- add a CLI flag to skip `--secure`

PRs are welcomed.

**Comment by codepuncher** [comment]
Just so you know, @sangemaru, opened an issue here for this https://github.com/cpriego/valet-linux/issues/369

**Comment by codepuncher** [comment]
@sangemaru , I submitted a patch which is now merged. That will solve your issue.
