### ISSUE TITLE
Brew tap is broken on arm-based macs

### ISSUE THREAD

**Issue by jamesknelson** [roots/trellis-cli#199]
## Description

On arm-based macs, when attempting to install via `brew install roots/tap/trellis-cli`, installation fails:

```
==> Tapping roots/tap
Cloning into '/opt/homebrew/Library/Taps/roots/homebrew-tap'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 93 (delta 0), reused 0 (delta 0), pack-reused 89
Receiving objects: 100% (93/93), 11.70 KiB | 2.93 MiB/s, done.
Resolving deltas: 100% (21/21), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/roots/homebrew-tap/Formula/trellis-cli.rb
formulae require at least a URL
Error: Cannot tap roots/tap: invalid syntax in tap!
```

It looks like this is due to the tap code generated by goreleaser, which checks if the CPU is an intel-based CPU, and if *not*, skips installation. See https://github.com/roots/homebrew-tap/blob/master/Formula/trellis-cli.rb#L11:

```ruby
  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roots/trellis-cli/releases/download/v1.0.0/trellis_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "e8ce7454201f5b5305ec7e58a2dcd2fe447d1c07808e70fb88fa57f5fc9701b0"

      def install
        bin.install "trellis"
      end
    end
  end
```

## Versions

v1.0.0

## Additional information

As arm-based macs can run intel binaries, this could be fixed by simply removing the `if` statement in the tap code. However, as it is generated by goreleaser, I'm not sure if this is possible. I've taken a look at the [goreleaser brew](https://goreleaser.com/customization/homebrew/) configuration, but couldn't find a simple fix.

Perhaps it would be possible to provide an ARM binary?

**Comment by swalkinshaw** [comment]
I think https://github.com/roots/trellis-cli/pull/200 should do it? Assuming that works, I'll try and it to the latest release.

Thanks for bringing this up!

**Comment by swalkinshaw** [comment]
It works, just need to figure out how to get it to re-publish the assets.

**Comment by swalkinshaw** [comment]
Well that was fun 😅  this exposed a few problems with our release process but it's all fixed now 🎉 

Check out https://github.com/roots/homebrew-tap/blob/master/Formula/trellis-cli.rb#L11 + there's ARM versions attached to the GH release. I _assume_ this should all be working.

**Comment by jamesknelson** [comment]
Thanks, the install is working great now! I'm still running into some issues with Trellis and my M1 Mac Mini. Will move discussion to https://github.com/roots/trellis/issues/1253 if I can't resolve them.
