### ISSUE TITLE
.vault_pass support

### ISSUE THREAD

**Issue by retlehs** [roots/trellis-cli#2]
`trellis new` should allow for creating a `.vault_pass`, setting the path to the vault_pass in `ansible.cfg`, and encrypting the files

**Comment by swalkinshaw** [comment]
This was mostly taken care of by #21 except for the actual encrypting part.

trellis-cli should offer more `vault` commands though.

**Comment by swalkinshaw** [comment]
Closed by https://github.com/roots/trellis-cli/pull/27
