### ISSUE TITLE
Trellis CLI deploy flag suggestion

### ISSUE THREAD

**Issue by jt-adwisemedia** [roots/trellis-cli#208]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

Add support for the `--limit` flag for the `trellis deploy <environment>` command, currently we have to write the entire `ansible-playbook deploy.yml -e env=production -e site=yoursite.tld --limit=kinsta_production`, would be nice if you could just write `trellis deploy production --limit=kinsta_production`.

## Motivation

Nice quality of life change, convenience.

**Comment by swalkinshaw** [comment]
Probably makes sense to support natively. In the meantime, I _think_ you could use extra vars:

```bash
trellis deploy --extra-vars ansible_limit=kinsta_production production
```

**Comment by swalkinshaw** [comment]
@jt-adwisemedia I assume you're using the `limit` option because of this guide? https://kinsta.com/blog/bedrock-trellis/

In most cases, `limit` shouldn't be needed at all because there's only one host per environment. Ie: one staging server, one production server, etc. 

We'll try and get that guide updated because `limit` seems redundant. This means you also don't need that option when using the CLI. You can verify this by just running `trellis deploy production` and making sure it does the same thing as with `--limit`.

If there's a difference, feel free to re-open this issue.

**Comment by dalepgrant** [comment]
@swalkinshaw I've come here looking for exactly this. Example of a use case [here in Roots Discourse](https://discourse.roots.io/t/best-practice-for-multiple-sites-on-multiple-servers/5385/6?u=dalepgrant).

We have our Trellis structured as follows:
```
trellis/
├── group_vars/         
    └── production/
        ├── main.yml
        └── vault.yml
    └── staging/
└── host_vars
    └── server1/
        └── wordpress_sites.yml
    └── server2/
    └── staging1/
    └── staging2/
```

Our deploy then looks like this with the old deploy.sh script:
```
./bin/deploy.sh production domain.example --limit=server1
```

Not strictly related to this issue, but if I try to run your suggestion while provisioning, trellis-cli gives an error

```
trellis provision --extra-vars ansible_limit=server1 production
Error: production is not a valid environment, valid options are [development]
```

**Comment by swalkinshaw** [comment]
Wait sorry I misread that error message. It's handling the command correctly but it's only detecting the `development` environment for some reason?

Do you not have a `wordpress_sites.yml` file under `production`? That's how it detect environments

**Comment by dalepgrant** [comment]
No, the `wordpress_sites.yml` files are under the `host_vars` folders, one per server so we can choose which site(s) sit where.

**Comment by swalkinshaw** [comment]
Opened a new issue for that: https://github.com/roots/trellis-cli/issues/278
