### ISSUE TITLE
Bug: `trellis db open --app=tableplus development <sitename>` unable to connect without selecting the VirtualBox private key

### ISSUE THREAD

**Issue by retlehs** [roots/trellis-cli#218]
### 

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

When running `trellis db open --app=tableplus development example.com`, TablePlus attempts to open a database connection to the development environment but the SSH connection fails

#### Temporary workarounds

Manually select the private key from `.vagrant/machines/default/virtualbox/private_key` via TablePlus

### Steps To Reproduce

1. macOS: Install TablePlus
1. From a Trellis site, run `trellis db open --app=tableplus development <sitename>`

### Expected Behavior

TablePlus opens with a connection established to the development environment

### Actual Behavior

TablePlus prompts for a SSH key private password

![image](https://user-images.githubusercontent.com/115911/145686472-795b7c52-6755-45a7-8b5c-0505ae26b784.png)

### Versions

v1.0.0

**Comment by swalkinshaw** [comment]
We'd need to know if Tableplus supports an SSH key param in the connection string:

`open "mysql+ssh://ssh-user@ssh-host:1234/example_com:db-password@db-host/db-name?usePrivateKey=true&enviroment=wp-env&ssl-key=(<path_to_trellis>/.vagrant/machines/default/virtualbox/private_key"`

If you replace those with real values you could test it.

I got `ssh-key` param from https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html#connecting-using-uri

**Comment by retlehs** [comment]
i forgot that trellis adds the vagrant SSH key into `~/.ssh/config` already, so this might be an issue upstream. will try to debug further soon

ref https://github.com/TablePlus/TablePlus/issues?q=is%3Aissue+is%3Aopen+ssh
ref https://tableplus.com/blog/2018/10/failed-to-connect-via-ssh-tableplus.html

**Comment by swalkinshaw** [comment]
I guess this is a common issue for development databases. trellis-cli can't easily specify the path to the private key (since it differs based on Vagrant provider), so we need to rely on each db app having a way to read your local SSH config.

Here's how it works with Sequel Ace: https://discourse.roots.io/t/advice-for-trellis-db-open-with-vagrant-dev-box/22002/3

**Comment by swalkinshaw** [comment]
Going to close this for now since it's up to the GUI app to support this properly.
