### ISSUE TITLE
Bug: Using a reference in /hosts/* causes key generation to fail

### ISSUE THREAD

**Issue by intelligence** [roots/trellis-cli#259]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Trying to use `trellis key generate` with the setup suggested for using Trellis on Kinsta causes a connection error

```
trellis key generate
[✓] Generated SSH key [/Users/xxx/.ssh/trellis_xxx_se_ed25519]
[✓] Moved public key [/Users/xxx/WWW/xxx.se/trellis/public_keys/trellis_xxx_se_ed25519.pub]
[✓] GitHub private key secret set [TRELLIS_DEPLOY_SSH_PRIVATE_KEY]
[✓] GitHub deploy key added [Trellis deploy]
Error: could not set SSH known hosts.
ssh-keyscan command failed for all hosts: [vps]
```

`/hosts/staging`:
```
vps ansible_host=x.x.x.x ansible_ssh_port=22 ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

[web]
vps

[staging]
vps
```

#### What insights have you gained?
```
 ansible all --list-hosts
  hosts (3):
    192.168.56.5
    your_server_hostname
    vps
```

#### Temporary workarounds
Setting the IP as reference
`/hosts/staging`:
```
x.x.x.x ansible_host=x.x.x.x ansible_ssh_port=22 ansible_ssh_extra_args='-o StrictHostKeyChecking=no'

[web]
x.x.x.x

[staging]
x.x.x.x
```

### Steps To Reproduce

Use a reference in `/hosts/*/` as per the Kinsta with Trellis guide: https://roots.io/guides/deploying-to-kinsta-with-trellis/

### Expected Behavior

Should pick up the IP from the reference, rather than the reference name

### Actual Behavior

Tries to connect to the reference name

### Versions

1.5.1

**Comment by swalkinshaw** [comment]
Sorry, missed this issue entirely somehow.

trellis-cli won't be able to "resolve" these ansible host references unfortunately; especially since `ansible all --list-hosts` doesn't even do that.

This specific known hosts feature has been a struggle from the start trying to auto-detect "real looking hosts" and it's still not perfect. I'm thinking the only solution to this is to abandon the attempt to do it all automatically and just have a prompt to entire the hostname/IP.
