### ISSUE TITLE
VirtualEnv fix for paths with spaces still not working

### ISSUE THREAD

**Issue by Bozzified** [roots/trellis-cli#281]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
Even though the latest 1.6 version should have addressed this as previously reported, the issue is still present.

#### What have you tried?
- Standard trellis-cli install (1.6) with **brew install roots/tap/trellis-cli** . Running **pyenv** with **3.10.3** python as global. Behaves the same with Python 3.9.6 as well.
- Ran with **trellis new pictionaryontv.com** on an external volume **"Data HD"**
- Vagrant 2.2.19 but behaves the same with 2.2.18

**ERROR:**
```
Error while initializing project in a directory path that contains spaces.
Python's virtualenv does not properly handle paths with spaces in them. trellis-cli attempted to automatically fix the bin scripts as a workaround but encountered an error:
rename /var/folders/cd/2ydcx0sn6ql28j_9pw255r7h0000gn/T/replace-ansible949728379 /Volumes/Data HD/Dropbox/Work/pictionary/pictionaryontv.com/trellis/.trellis/virtualenv/bin/ansible: cross-device link
As an alternative, you can re-create this project in a path without spaces.
Or you can open an issue to let us know: https://github.com/roots/trellis-cli
Error while installing Ansible Galaxy roles:

This may be a temporary network issue. Please try again
```

#### What insights have you gained?
Seems like the fix for 1.6 is still not working with spaces in paths

#### Possible solutions
As suggested it works on a volume with no spaces in the path but since I have tons of projects on the volume it is an issue. 

#### Temporary workarounds
Manually pulling Trellis setup without using the CLI is another workaround.

### Steps To Reproduce

1. Projects folder on external volume with spaces in it
2. Run trellis new
3. After Dependencies Installed the error pops up

### Expected Behavior

Due to the latest fix in 1.6 expectation was that workaround for paths with spaces would finish setting up new trellis project successfully.

### Actual Behavior

Error while initializing project in a directory path that contains spaces still persists.

### Versions

OSX Big Sur, Python 3.10.3, Trellis CLI 1.6

**Comment by swalkinshaw** [comment]
Thanks for the detailed issue!

Here's the key part:

> rename /var/folders/cd/2ydcx0sn6ql28j_9pw255r7h0000gn/T/replace-ansible949728379 /Volumes/Data HD/Dropbox/Work/pictionary/pictionaryontv.com/trellis/.trellis/virtualenv/bin/ansible: cross-device link

It's trying to rename (move) a file _across_ different volumes/filesystems which isn't supported.

https://github.com/roots/trellis-cli/pull/282 should fix it by copying the file over instead.

**Comment by swalkinshaw** [comment]
I'll release 1.6.1 soon 🚀
