### ISSUE TITLE
Feature Request: specify owner/repo for `key generate`

### ISSUE THREAD

**Issue by codepuncher** [roots/trellis-cli#286]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Currently, when running `trellis key generate`, `gh secret set` will automatically pick the remote to set the secret to.
This is great for most cases, but allowing a user to specify a remote to set the secret on would be helpful to some.

#### Why are we doing this?
To allow setting a secret to a specific remote.

#### What use cases does it support?
If you have more than 1 remote (e.g. you have an `origin` remote and an `upstream` remote pointing to your maintained Trellis fork) then running `trellis key generate` (from my tests) always sets the secrets on the wrong remote.
This feature request would allow explicitly specifying the correct remote or owner/repo. 

#### What is the expected outcome?
Running `trellis key generate` with an optional flag to specify the remote or owner/repo would set the secrets to the expected repo.

#### Potential conflicts / foreseeable issues
None that I can think of; not specifying the remote repo would just result in the current behaviour.

### Additional Context

We use separate Trellis and Bedrock repositories for our preferred organisation of projects.

Also, we have a [tool we use internally](https://github.com/ItinerisLtd/iroots) to spin up projects from our maintained Bedrock and Trellis forks then configure and deploy with trellis-cli.

I plan to add support to the tool for automating `trellis key generate` during the project setup.
However, this is not currently possible due to the local repositories have 2 remotes and `trellis key generate`/`gh secret set` using on the wrong remote.

**Comment by codepuncher** [comment]
Since `gh secret set --repo` can also use a remote as the value (format is [`<[HOST/]OWNER/REPO>`](https://cli.github.com/manual/gh_secret_set#options-inherited-from-parent-commands)) e.g.  `https://github.com/roots/trellis-cli.git`, would it be better to name the flag `--remote`? Or would you rather keep it the as `--repo` same as `gh`?

**Comment by swalkinshaw** [comment]
I'd probably rather `--repo`. For consistency but also I think it would be more common for people to think in terms of repo vs remote.
