### ISSUE TITLE
Feature Request: Specify user for `trellis ssh`

### ISSUE THREAD

**Issue by codepuncher** [roots/trellis-cli#290]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

Currently, `trellis ssh ENVIRONMENT` uses hardcoded users (as per #46).
This prevents you from using the command if `admin` is not the user you wish to use.

#### Why are we doing this?
To allow connecting to the server with a user other than the hardcoded `admin` user.

#### What use cases does it support?
You may not use `admin` as your `web_user`, `admin_user` or other system user so the command is of no use for you.

#### What is the expected outcome?
To be able to SSH into the server using a user other than `admin`.
Perhaps to make use of the `web_user`, `admin_user` or to specify a user as a command flag is how the feature could be used.

#### Potential conflicts / foreseeable issues
N/A

### Additional Context

I want to SSH into a managed host (e.g. Kinsta) so this would be useful to support.
We set the `web_user` variable to our Kinsta site user in `group_vars/{staging,production}/users.yml`

**Comment by swalkinshaw** [comment]
A `--user` flag would be the easiest way to do by far so we should probably start with that.

Weirdly trellis-cli can't easily know about arbitrary Ansible variables (beyond wordpress sites) since it would have to parse the YML manually and wouldn't be group/environment aware either. It's possible to make trellis-cli execute temporary playbooks to get the value of a variable (like `web_user`) but then it makes the commands much slower.

**Comment by codepuncher** [comment]
Cool; I'll look to submit a PR for that soon then cheers

**Comment by codepuncher** [comment]
I have realised that, for my use case, this feature is now pointless.

For Kinsta setup, we use Ansible host aliases to also specify the SSH port so the current ssh format doesn't work.
Of course we can just add more flags to cover the differences like port and host, but then I may as well just directly run `ssh`.

Also, without the additional flags, the ssh subcommand would need more changes as SSH on Kinsta does not work on the canonical domain in group vars; it must be the Ansible host IP address.

Any thoughts on the above or shall I just abandon this, @swalkinshaw? It would be great to use `trellis ssh` for Kinsta sites but I am not sure what the best approach would be for that anyway.

**Comment by swalkinshaw** [comment]
Yeah good point... I've thought of this before and came to a similar conclusion. Basically `trellis ssh` is convenient for default cases. Anything beyond that, we shouldn't try to replicate all the options people might need for SSH connections so we should encourage SSH aliases instead.

`trellis ssh` also tries to SSH into the site's host and _not_ the hosts in the inventory `hosts` file which is a bit weird.

**Comment by codepuncher** [comment]
Good tip on SSH aliases; didn't know about that!

I haven't found an "ansible way" to get the IP address from a host alias so it requires manual parsing.
As you mentioned, `trellis ssh` is convenient for default cases.
With SSH aliases in mind, I think I'll just close this off then; I can create the aliases in our project setup tool to fit our use case.
