### ISSUE TITLE
Bug: `$PATH` variable gets corrupted when adding Virtualenv shell integration

### ISSUE THREAD

**Issue by vasartam** [roots/trellis-cli#295]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Description

Recently I tried to install a new local site using Trellis.

I am using WSL 2 with Debian 11 instance.

#### What's wrong?

The `$PATH` variable gets corrupted when using Virtualenv shell integration feature.

#### What have you tried?

Tried adding Virtualenv shell integration, as described in the [Shell integration section in README.md](https://github.com/roots/trellis-cli#virtualenv).

#### What insights have you gained?

Trellis Virtualenv shell integration fails to work with spaces or quotes inside `$PATH`.

#### Possible solutions

Didn't come up with one.

#### Temporary workarounds

Do not use the Virtualenv shell integration feature.

### Steps To Reproduce

1. Open WSL bash terminal.
2. `echo $PATH` - remember that to compare with the value next steps later.<details><summary>An example of output</summary><pre>/home/vartamonov/.local/bin:/home/vartamonov/.nvm/versions/node/v17.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Python310/Scripts/:/mnt/c/Program Files/Python310/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/Inkscape/bin:/mnt/c/Program Files/Common Files/Autodesk Shared/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/:/mnt/c/Users/artam/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/artam/AppData/Roaming/npm</pre></details>
3. `eval "$(trellis shell-init bash)"`
4. `cd` into the folder with the freshly installed project using Trellis.
5. Receive the following message: `[trellis] activated env`.
6. `echo $PATH` - the value is now prepended with a path to the Virtualenv bin (`/path/to/project/trellis/.trellis/virtualenv/bin:`), however the rest of the old value is enclosed in single quotes `''`.<details><summary>An example of output</summary><pre>/var/www/mih-art.loc/trellis/.trellis/virtualenv/bin:'/home/vartamonov/.local/bin:/home/vartamonov/.nvm/versions/node/v17.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Python310/Scripts/:/mnt/c/Program Files/Python310/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files/nodejs/:/mnt/c/Program Files/Inkscape/bin:/mnt/c/Program Files/Common Files/Autodesk Shared/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/:/mnt/c/Users/artam/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/artam/AppData/Roaming/npm'</pre></details>
7. `cd` into the folder up to exit env: `cd ..`
8. Receive the following message: `[trellis] deactivated env`.
9. `cd` into the folder with the project again.
10. Receive the message `[trellis] activated env`, as well as a lot of `not a valid identifier` errors (depends on the number of software installed).<details><summary>An example of output</summary><pre>[trellis] activated env<br>-bash: export: \`Files/Python310/Scripts/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Python310/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/nodejs/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Inkscape/bin:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Common': not a valid identifier<br>-bash: export: \`Files/Autodesk': not a valid identifier<br>-bash: export: \`Shared/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/:/mnt/c/Users/artam/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/artam/AppData/Roaming/npm"''': not a valid identifier<br>-bash: export: \`Files/Python310/Scripts/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Python310/:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/nodejs/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Inkscape/bin:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Common': not a valid identifier<br>-bash: export: \`Files/Autodesk': not a valid identifier<br>-bash: export: \`Shared/:/mnt/c/Program': not a valid identifier<br>-bash: export: \`Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python38/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/Scripts/:/mnt/c/Users/artam/AppData/Local/Programs/Python/Python37/:/mnt/c/Users/artam/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/artam/AppData/Roaming/npm"''': not a valid identifier</pre></details>
11. `echo $PATH`<details><summary>An example of output</summary><pre>/var/www/mih-art.loc/trellis/.trellis/virtualenv/bin:''"/home/vartamonov/.local/bin:/home/vartamonov/.nvm/versions/node/v17.6.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program</pre></details>

### Expected Behavior

The value of `$PATH` that is output on the step 6 and on the last step is the same as the value on the step 2, except it is prepended with `/path/to/project/trellis/.trellis/virtualenv/bin:`.

### Actual Behavior

1. The value of `$PATH` that is output on the step 6 is the same as the value on the step 2, except it is prepended with `/path/to/project/trellis/.trellis/virtualenv/bin:`, and the rest of the `$PATH` value is enclosed in single quotes `''`.
2. The value of `$PATH` that is output on the last step is the same as the value on the step 2, except it is prepended with `/path/to/project/trellis/.trellis/virtualenv/bin:`, two single quotes `''`, one double quote `"` and trimmed to the first found space character.

### Similar issues

#142

### Versions

1.6.1

**Comment by vasartam** [comment]
I guess the problem lies somewhere around these lines of code:

https://github.com/roots/trellis-cli/blob/a389115eb35e3c322e084183dc41497ffd67e7e0/cmd/venv_hook.go#L25-L27

Can't actually what's wrong here as I'm not familiar with Go

**Comment by swalkinshaw** [comment]
Thanks for the detailed issue @vasartam 

I think `shellescape` is fine but there is two other problems:

1. double quoting - I use shellescape *and* double quoted the values
2. `PATH` gets exported with quotes surrounding the Trellis path and the old (full) path instead of the entire value (`\"%s\":\"%s\""` instead of `\"%s:%s\""`)

https://github.com/roots/trellis-cli/pull/296 should simplify and correct things but I need to test it more locally

**Comment by swalkinshaw** [comment]
I'll release a new version soon but this is working for me now

**Comment by vasartam** [comment]
@swalkinshaw, isn't this issue specific to the environment I ran trellis-cli in?

Did it work correctly earlier for all other users before me? Won't new changes break something for non-WSL environments?

**Comment by swalkinshaw** [comment]
WSL shouldn't really matter here since it's just Linux.

Honestly I don't know if it worked for everyone in all cases, but the issues I mentioned in https://github.com/roots/trellis-cli/issues/295#issuecomment-1127102226 were just wrong regardless of environment. I'm on macOS and these new changes worked for me as well (in a path with spaces and without).

Also this whole investigation made me discover another bug that I fixed in https://github.com/roots/trellis-cli/issues/295#issuecomment-1127102226 😄

**Comment by vasartam** [comment]
Nice, glad it helped!
