### ISSUE TITLE
Info should properly show site hosts per environment

### ISSUE THREAD

**Issue by retlehs** [roots/trellis-cli#3]
right now the output of `trellis info` is:

```
development => example.com
production => example.com, example.com
staging => example.com, example.com, example.com
```

based on the trellis defaults, this should probably instead return:

```
development => example.test, www.example.test
production => example.com, www.example.com
staging => staging.example.com
```

**Comment by swalkinshaw** [comment]
`staging => example.com, example.com, example.com`

well that's definitely a bug.

However, this command was designed to show the site *names* at least so not technically a bug. But we should show hosts separately too.
