### ISSUE TITLE
`trellis new`: improve support for non-domain path/names

### ISSUE THREAD

**Issue by neilgilmour** [roots/trellis-cli#31]
Prior to v0.3.0, doing something like `trellis new example` would create a directory called `example` and then prompt for the project name. Now in v0.3.0 it produces the following error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1472a11]

goroutine 1 [running]:
trellis-cli/cmd.askDomain(0x1649be0, 0xc0000a08c0, 0xc000026e20, 0x1c, 0x1, 0xc0000202c0, 0x3d, 0x40)
	/home/travis/gopath/src/github.com/roots/trellis-cli/cmd/new.go:216 +0x81
trellis-cli/cmd.(*NewCommand).Run(0xc0000a09b0, 0xc00001c0e0, 0x1, 0x1, 0xc00000b660)
	/home/travis/gopath/src/github.com/roots/trellis-cli/cmd/new.go:86 +0x22c
github.com/mitchellh/cli.(*CLI).Run(0xc0000e5180, 0xc000182060, 0x15a0996, 0xa)
	/home/travis/gopath/pkg/mod/github.com/mitchellh/cli@v1.0.0/cli.go:255 +0x207
main.main()
	/home/travis/gopath/src/github.com/roots/trellis-cli/main.go:75 +0xae0
```

 If no .tld is present in the `trellis new` command, perhaps a solution would be a prompt asking for it.

**Comment by MikaCaldera** [comment]
Did you ever find a solution for things? I am running into the same error and not finding any solutions.

**Comment by neilgilmour** [comment]
Yes. I just change the directory name after it has been created.

**Comment by swalkinshaw** [comment]
There's probably a better solution for this, but for now I have a "fix" up to at least handle the exception and return a nice error message: https://github.com/roots/trellis-cli/pull/45.

I'll leave this open though.

**Comment by swalkinshaw** [comment]
I'm considering this closed now after https://github.com/roots/trellis-cli/pull/58.

You can do `trellis new --name example.com --host example.com foo`
