### ISSUE TITLE
Can't quit `trellis new domain.tld`

### ISSUE THREAD

**Issue by codepuncher** [roots/trellis-cli#34]
Just downloaded version 0.3.0 and ran `trellis new gutenburg.test` and decided to use a different TLD so I went to quit the process with CTRL+C.
Expected it to quit but instead, it just kept reprinting the `Site domain` prompt

![image](https://user-images.githubusercontent.com/8135396/52819952-938f7b80-30a2-11e9-8c7a-49bd60ce366e.png)

If I choose a new domain from the suggestions, I can then quit.

![image](https://user-images.githubusercontent.com/8135396/52820042-ca659180-30a2-11e9-8e70-2fca506dbb4d.png)

Using Ubuntu 18.04 and zsh 5.4.2.

**Comment by swalkinshaw** [comment]
Yeah I ran into this last night too and forgot to create an issue 😔 Should be an easy fix

**Comment by swalkinshaw** [comment]
Also ideally "Other" appears last in the list
