### ISSUE TITLE
Bug: CLI install script: HTTP 404 for release ZIP

### ISSUE THREAD

**Issue by strarsis** [roots/trellis-cli#347]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
The Trellis CLI install script uses an incorrect URL for downloading the release ZIP, resulting in a HTTP 404 (File not found).

#### What have you tried?
Invoked the command from README, checked the CLI script, the correct release ZIP URL.

#### What insights have you gained?
The [script](https://raw.githubusercontent.com/roots/trellis-cli/master/scripts/get) generates the wrong URL for downloading the release ZIP.

#### Possible solutions
Making the install script more robust so that it also supports ZIP files that don't follow the currently expected naming scheme.

#### Temporary workarounds
Manually download the release file (https://github.com/roots/trellis-cli/releases/download/v1.9.0/trellis_Linux_x86_64.tar.gz), extract it (e.g. `tar -xzvf trellis_Linux_x86_64.tar.gz`), move new `trellis` binary to PATH (e.g. `mv ./trellis $(which trellis)`).

### Steps To Reproduce

1. Run Trellis CLI install script.
Note that installation fails.

### Expected Behavior

Install script installs Trellis CLI.

### Actual Behavior

Install script fails installing latest Trellis CLI with HTTP 404.

### Relevant Log Output

```shell
roots/trellis-cli info checking GitHub for latest tag
roots/trellis-cli debug http_download https://github.com/roots/trellis-cli/releases/latest
roots/trellis-cli info found version: 1.9.0 for v1.9.0/Linux/x86_64
roots/trellis-cli debug downloading files into /tmp/tmp.NF87d1h85a
roots/trellis-cli debug http_download https://github.com/roots/trellis-cli/releases/download/v1.9.0/trellis_1.9.0_Linux_x86_64.tar.gz
roots/trellis-cli debug http_download_curl received HTTP status 404
```

### Versions

Trellis CLI 1.8.0

**Comment by swalkinshaw** [comment]
Weird... not sure when GitHub changed their download URL format but I've fixed it in https://github.com/roots/trellis-cli/pull/348

Thanks for reporting
