### ISSUE TITLE
Bug: trellis vault edit staging "no such file"

### ISSUE THREAD

**Issue by cspicuzza** [roots/trellis-cli#356]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?

`trellis vault edit staging`  throws an error

#### What have you tried?

`trellis vault view staging` -> works
`trellis vault edit staging` -> fails

#### What insights have you gained?

I can edit the file with 
`ansible-vault edit group_vars/staging/vault.yml`

### Steps To Reproduce

1. Install Trellis using the cli
2. configure group_vars
3. trellis vault encrypt
4. trellis vault edit staging

### Expected Behavior

I expected to be able to edit my vault file

### Actual Behavior

 [Errno 2] No such file or directory: '/Users/**/Development/***.com/trellis/staging'

### Versions

trellis cli 1.9.0

**Comment by swalkinshaw** [comment]
This isn't technically a bug because it's the expected and documented behaviour. This command requires a file path, not an environment name:

```plain
trellis vault edit
Error: missing arguments (expected exactly 1, got 0)

Usage: trellis vault edit [options] FILE

Edit an encrypted file in place

Trellis docs: https://docs.roots.io/trellis/master/vault/
Ansible Vault docs: https://docs.ansible.com/ansible/latest/user_guide/vault.html

Edit production file:

  $ trellis vault edit group_vars/production/vault.yml

Arguments:
  FILE file name to edit

Options:
  -h, --help  show this help
```

However, right now the `vault` commands have a few inconsistencies and I agree it ideally _should_ work this way. But there are differences with `edit` that make it a bit harder.

I'm leaving this open since I'm going to try and make all the vault commands more consistent.

**Comment by cspicuzza** [comment]
That makes sense. Sorry for reporting a non-bug
