### ISSUE TITLE
Feature Request: Allow parameters to be passed with trellis vm shell

### ISSUE THREAD

**Issue by robrecord** [roots/trellis-cli#377]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

### Summary

As I understand it, `trellis vm shell` is a wrapper for `limactl shell <project_name>`. Until recently, the [lima docs incorrectly reported the order of parameters](https://github.com/lima-vm/lima/pull/1444
). Now it's `limactl shell [<options>] <project_name> [<command>]`. Could it be possiblt to allow trellis-cli to pass options such as `--workdir`, or even set them automatically?

So trellis vm shell would be a wrapper for `limactl shell --workdir /srv/www/<project_name>/current <project_name>` and would include any user-specified extra params before the <project_name>, and anything else after a `--`.

Hope that makes sense?

#### Why are we doing this?

1. allow directly CDing into correct dirctory
2. allow user passing of params
3. allow separation between params and command
4. currently it is impossible to pass any parameters (such as workdir) to limactl

#### What use cases does it support?

Better use of SSH into VM

#### What is the expected outcome?

More control and convenience

### Additional Context

https://github.com/lima-vm/lima/pull/1444

with trellis:
```
❯ trellis vm shell --workdir /srv/www/example.com/current
Running command => limactl shell example.com --workdir /srv/www/example.com/current
bash: line 1: cd: /Users/me/Code/Projects/Sites/example.com/trellis: No such file or directory
bash: line 1: cd: /Users/me: No such file or directory
/bin/bash: --: invalid option
```

with limactl:
```
❯ limactl shell --workdir /srv/www/example.com/current example.com
me@lima-example:/srv/www/example.com/current$
```

**Comment by swalkinshaw** [comment]
I had planned on setting `--workdir` to either `/srv/www/example.com` or  `/srv/www/example.com/current` automatically as a default. We could also let people override that in the CLI config file.

Additionally, I do think a flag override would be helpful too.

I've also thought about just mounting those two default dirs so lima doesn't complain; it's annoying they don't a way to avoid that. I could always contribute an upstream fix 🤷‍♂️
