### ISSUE TITLE
[bug] trellis alias causing bud build to throw warning

### ISSUE THREAD

**Issue by chrillep** [roots/trellis-cli#397]
### Version

latest

### What did you expect to happen?

aliases to be correct

### What actually happens?

yarn build
yarn run v1.22.19
$ yarn bud build production
[fs] [wp-cli.trellis-alias.yml] › ⚠  wp-cli.trellis-alias.yml causes an exception when read.
Since wp-cli.trellis-alias.yml does not appear to be a bud configuration file, bud.js is not throwing. Original error follows:

BudError: end of the stream or a document separator is expected (1:1)

 1 | @development:
-----^

### Steps to reproduce

run trellis aliases
run yarn build

### System info

great system

### Log output

```shell
[fs] [wp-cli.trellis-alias.yml] › ⚠  wp-cli.trellis-alias.yml causes an exception when read.
Since wp-cli.trellis-alias.yml does not appear to be a bud configuration file, bud.js is not throwing. Original error follows:

BudError: end of the stream or a document separator is expected (1:1)

 1 | @development:
-----^
```

### Please confirm this isn't a support request.

Yes

relates to: https://github.com/roots/bud/issues/2332

**Comment by chrillep** [comment]
if this belongs in radicle and or bud whatnot please keep reference and add the same ticket there

**Comment by swalkinshaw** [comment]
You cross-posted so I'll wait for @kellymears to chime in. Right now I have no how Bud integrates with this WP-CLI config.

**Comment by chrillep** [comment]
> You cross-posted so I'll wait for @kellymears to chime in. Right now I have no how Bud integrates with this WP-CLI config.

yeah i couldnt help myself :) 
just thought it was interconnected so both repo/users should know

**Comment by chrillep** [comment]
https://github.com/roots/bud/issues/2332#issuecomment-1605024519

**Comment by swalkinshaw** [comment]
Closing this since it's just a Bud issue. It seems weird that Bud would load any random yml file in a project root and error if its not valid...

**Comment by chrillep** [comment]
yeah,  from my standpoint i just want the warning gone :) .

for now i have to to quote the strings, so other teammates dont start to wonder what im doing :)
