### ISSUE TITLE
Vault encrypt command fails on encrypted files

### ISSUE THREAD

**Issue by neilgilmour** [roots/trellis-cli#42]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

When using the command `trellis vault encrypt <environment>` the files encrypted are `group_vars/all/vault.yml group_vars/<ENVIRONMENT>/vault.yml`. However if you then encrypt a different environment, it tries to encrypt `group_vars/all/vault.yml` again and fails.

## Steps to reproduce

1. Set up new trellis project `trellis new example.com`
2. Encrypt one environment `trellis vault encrypt development` 
3. Try to encrypt another one `trellis vault encrypt staging`

**Expected behavior:** [What you expect to happen]

If the command is run with no environment specified, it would be great to encrypt all vault.yml files, and not fail if some are already encrypted.

If run with an environment, skip files that are already encrypted.

**Actual behavior:** [What actually happens]

```
➜  trellis trellis vault encrypt production
Running command => ansible-vault encrypt group_vars/all/vault.yml group_vars/production/vault.yml
Encryption successful
➜  trellis trellis vault encrypt staging   
Running command => ansible-vault encrypt group_vars/all/vault.yml group_vars/staging/vault.yml
ERROR! input is already encrypted
```

**Reproduces how often:** [What percentage of the time does it reproduce?]

Every time I've tried it. Also while decrypting.

## Versions

Trellis-cli 0.3.1
Mac OS Mojave 10.14.4 (18E226)

## Additional information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by swalkinshaw** [comment]
Got a fix up here: https://github.com/roots/trellis-cli/pull/44
