### ISSUE TITLE
❤️ as a developer i need to generate a .vault_pass file when cloning a template repo using radicle/trellis so we can have better boilerplates

### ISSUE THREAD

**Issue by chrillep** [roots/trellis-cli#425]
### Summary

when using radicle/trellis boilerplates.
I need a way to generate a new .vault_pass via command.
So exposing the already existing function as a subcommand seems fitting :)

https://github.com/roots/trellis-cli/blob/31008804a85cadf7f36bb900ecd1e4250e57548a/trellis/vault.go#L116-L125

`trellis new vault-pass`

**Comment by codepuncher** [comment]
suggest `trellis vault pass new` since `trellis vault` is an existing namespace
also opens future possibility for `trellis vault pass edit` or others

**Comment by chrillep** [comment]
yeah the name ill let u guys decide. it was just an example :) 
the functionality however, is gold! :)

**Comment by codepuncher** [comment]
Yeah, I too would find this useful in project setup scripts; currently generating them myself.

**Comment by swalkinshaw** [comment]
Seems reasonable but just wondering why the file generate during `trellis new` isn't enough here? It is for existing projects?

**Comment by swalkinshaw** [comment]
I'm not against this yet, but it's pretty easy to script your own vault file too; especially if you're already writing scripts around other commands. Example:

```bash
LC_ALL=C tr -dc '[:alpha:]' </dev/urandom | head -c 64 > pass_file
```

**Comment by codepuncher** [comment]
Perhaps @chrillep is doing the same as me; I do not use `trellis new` because of having own project setup scripts. Not a big feature to have as we already generate vault pass ourselves but would be "nice" to use `trellis` to do this

**Comment by chrillep** [comment]
> Seems reasonable but just wondering why the file generate during `trellis new` isn't enough here? It is for existing projects?

yes its for existing projects  :)
and for new projects based on templates.

> I'm not against this yet, but it's pretty easy to script your own vault file too; especially if you're already writing scripts around other commands. Example:
> 
> ```shell
> LC_ALL=C tr -dc '[:alpha:]' </dev/urandom | head -c 64 > pass_file
> ```
we script it now.
But the code is already there in trellis-cli, so why create another wheel? that was my thinking. Same goes for the salts.

i might have missed something in https://github.com/roots/radicle/blob/main/.radicle-setup/trellis.php

but i cant find `trellis new` there? =) 

As always thanks for quality code! ❤️

**Comment by swalkinshaw** [comment]
> But the code is already there in trellis-cli, so why create another wheel? that was my thinking. Same goes for the salts.

The code is there but it's very simple and not really too Ansible/Trellis specific; it's just generating a random string into a file. It's important to handle it during `trellis new` because the expectation is you get a working project so it would be a bad user experience to _not_ handle that in that context.

But for more power users with different use cases, it shouldn't be an expectation for trellis-cli to offer a command for everything. There's a downside in terms of command bloat and developer experience.

In terms of Radicle, maybe it could detect if `trellis` is installed and optionally use that. @retlehs can provide more context on how it's designed this way

**Comment by swalkinshaw** [comment]
Going to close this as it can easily be scripted. https://github.com/roots/radicle/issues/99 might remove the need entirely anyway
