### ISSUE TITLE
Lima VM creation fails: no MariaDB 10.6 package for Ubuntu 24.04

### ISSUE THREAD

**Issue by ko-bra** [roots/trellis-cli#450]
### Version

1.12.0

### What did you expect to happen?

Lima VM creation succeeds with new default Ubuntu version (24.04).

### What actually happens?

Lima VM creation fails due to missing MariaDB 10.6 package for noble (24.04):

> fatal: default: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://mirror.rackspace.com/mariadb/repo/10.6/ubuntu noble Release' does not have a Release file."}

### Steps to reproduce

1. Create a new Trellis project with trellis-cli 1.12.0
2. Create a new Lima VM with `trellis vm start`

### System info

System Version:	macOS 14.3.1 (23D60)
Kernel Version:	Darwin 23.3.0
Chip:			M1 Pro

### Please confirm this isn't a support request.

Yes

**Comment by ko-bra** [comment]
I am assuming there is an unreleased fix on Trellis already that [bumps the MariaDB version](https://github.com/roots/trellis/pull/1520), but wanted to highlight that Trellis and trellis-cli are not in an consistent state as of now.

**Comment by swalkinshaw** [comment]
This should be considered fixed now
