### ISSUE TITLE
(Install script): `err hash_sha256_verify checksum`

### ISSUE THREAD

**Issue by strarsis** [roots/trellis-cli#490]
### Version

1.12.1

### What did you expect to happen?

Trellis CLI installation script should install newest Trellis CLI, also on a system where an older Trellis CLI is already present.

### What actually happens?

Error message that checksum did not verify.

### Steps to reproduce

- Install Trellis CLI version `1.12.1` by script method:
- Install (update) latest Trellis CLI version `v1.13.0` by using the script method again.
Installation fails with checksum error message (see the Log output below).

### System info

Ubuntu `24.04.1` LTS on WSL `2` (Windows `10` x64).

### Log output

```shell
curl -sL https://roots.io/trellis/cli/get | bash
roots/trellis-cli info checking GitHub for latest tag
roots/trellis-cli info found version: 1.13.0 for v1.13.0/Linux/x86_64
roots/trellis-cli err hash_sha256_verify checksum for '/tmp/tmp.4WZmFM543j/trellis_Linux_x86_64.tar.gz' did not verify 0a121dc4ec7b1ff12dd24485483d1977da1ef2cc2354821e3ee364bede12adea
0d4d0712ab1bfddbc727dcabdc6a2ab568805b37ccf20255a0bcb4f13ae65f3f vs 0a121dc4ec7b1ff12dd24485483d1977da1ef2cc2354821e3ee364bede12adea
```

### Please confirm this isn't a support request.

Yes

**Comment by mihalikv** [comment]
Same issue here

**Comment by swalkinshaw** [comment]
🤔 interesting. Let me try re-creating it as a first step

**Comment by swalkinshaw** [comment]
Done, if that doesn't work I'll have to dig into the install script and the release process

**Comment by LucasDemea** [comment]
Still not working on my side

**Comment by swalkinshaw** [comment]
Okay thanks, I'll have to dig into the install script later to see what's happening

**Comment by swalkinshaw** [comment]
Well that was a fun one... fixed 🚀
