### ISSUE TITLE
`open` in browser command

### ISSUE THREAD

**Issue by knowler** [roots/trellis-cli#76]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing request
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Summary

I propose adding a new command, `trellis open`, to allow users to open the website in a browser. The full command schema would probably be something like:

`trellis open [options] ENVIRONMENT SITE`

## Motivation

`trellis open` would open the default environment in a browser. Inspiration for this is Laravel Valet and Netlify’s `open` command which do exactly that (the former for development, the latter for production).

## Additional context

Some things to consider would be:

* Which environment should be considered default? I think `development` should be, since I could see the command being most used in this environment.
* How does this behave for when multiple sites are on the same server? Of course, multiple sites on the same server isn’t ideal, but it is possible with Trellis. It could offer an selection menu, so that the command wouldn’t be useless in this context.
* An idea to tag on to this would be something like Netlify’s `open:admin` command which opens the admin dashboard for the website. It could offer to install [aaemnnosttv/wp-cli-login-command](https://github.com/aaemnnosttv/wp-cli-login-command) as well to make the transition more seamless. We could always just name this command `login`.

**Comment by swalkinshaw** [comment]
👍 I have this at work on our dev tool and it's very useful. If we wanted to go a step further beyond the default, we can let people define additional static entries in the local trellis config (which doesn't exist yet).

```yaml
open:
  newrelic: <url>
  sentry: <url>
```

Very useful for any additional URLs related to the project.

**Comment by swalkinshaw** [comment]
Got an implementation of this up in https://github.com/roots/trellis-cli/pull/228
